name: footballnews_mobile
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.6 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.8
  get: 4.6.6
  flutter: 
    sdk: flutter
  cloud_firestore: ^4.15.8
  firebase_auth: ^4.17.8
  firebase_messaging: ^14.7.19
  flutter_local_notifications: ^18.0.1
  speech_to_text: ^6.6.0
  get_storage: ^2.1.1
  dio: ^5.7.0
  http: ^1.2.0
  webview_flutter: ^4.8.0
  shared_preferences: ^2.2.3
  permission_handler: ^11.3.1
  audioplayers: ^5.2.1
  video_player: ^2.9.1
  image_picker: ^1.0.8
  geolocator: ^11.1.0
  geocoding: ^3.0.0
  google_maps_flutter: ^2.5.3
  url_launcher: ^6.3.0
  carousel_slider: ^5.0.0
  firebase_storage: ^11.6.9
  file_picker: ^8.0.0+1
  connectivity_plus: ^6.1.1

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/audio/success.mp3

