// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEiHoSMMRlIKtHSu2TfmjSf8vRvETyifs',
    appId: '1:794898384745:web:5ea0e8ec170cdf901fdff8',
    messagingSenderId: '794898384745',
    projectId: 'footballnews-mobile',
    authDomain: 'footballnews-mobile.firebaseapp.com',
    storageBucket: 'footballnews-mobile.firebasestorage.app',
    measurementId: 'G-5HKH1WQ3S5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRhjRI1wJZS1lryvfb4sXKaOmZHy3Uyp8',
    appId: '1:794898384745:android:168decfdb991ebb51fdff8',
    messagingSenderId: '794898384745',
    projectId: 'footballnews-mobile',
    storageBucket: 'footballnews-mobile.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzgWffrJJUTUK7OdGsGDcvEx6Arj1yZWY',
    appId: '1:794898384745:ios:daeb8603448367ed1fdff8',
    messagingSenderId: '794898384745',
    projectId: 'footballnews-mobile',
    storageBucket: 'footballnews-mobile.firebasestorage.app',
    iosBundleId: 'com.example.footballnewsMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzgWffrJJUTUK7OdGsGDcvEx6Arj1yZWY',
    appId: '1:794898384745:ios:daeb8603448367ed1fdff8',
    messagingSenderId: '794898384745',
    projectId: 'footballnews-mobile',
    storageBucket: 'footballnews-mobile.firebasestorage.app',
    iosBundleId: 'com.example.footballnewsMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEiHoSMMRlIKtHSu2TfmjSf8vRvETyifs',
    appId: '1:794898384745:web:dcc8dc168cc40a941fdff8',
    messagingSenderId: '794898384745',
    projectId: 'footballnews-mobile',
    authDomain: 'footballnews-mobile.firebaseapp.com',
    storageBucket: 'footballnews-mobile.firebasestorage.app',
    measurementId: 'G-Z7FCWJFPXX',
  );
}
